// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLNBP0eVaRGWdTb3OvmIbA4tUCoHCqwzo',
    appId: '1:1034405989724:web:3e44d0fd4b80506b820599',
    messagingSenderId: '1034405989724',
    projectId: 'study-app-fcc70',
    authDomain: 'study-app-fcc70.firebaseapp.com',
    storageBucket: 'study-app-fcc70.appspot.com',
    measurementId: 'G-VX8LR5WT5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnqgpcIv04NwjazB63dgTFRn6Gh-VR_B0',
    appId: '1:1034405989724:android:989ac9ef2e5aa7e9820599',
    messagingSenderId: '1034405989724',
    projectId: 'study-app-fcc70',
    storageBucket: 'study-app-fcc70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUw103z9pY2Qk8uE0zDqWEHjeo9Rdy354',
    appId: '1:1034405989724:ios:4e1162145bad8286820599',
    messagingSenderId: '1034405989724',
    projectId: 'study-app-fcc70',
    storageBucket: 'study-app-fcc70.appspot.com',
    iosClientId: '1034405989724-ipcjneh2nk3p2gu40tflh7navsfcckhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUw103z9pY2Qk8uE0zDqWEHjeo9Rdy354',
    appId: '1:1034405989724:ios:4e1162145bad8286820599',
    messagingSenderId: '1034405989724',
    projectId: 'study-app-fcc70',
    storageBucket: 'study-app-fcc70.appspot.com',
    iosClientId: '1034405989724-ipcjneh2nk3p2gu40tflh7navsfcckhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
